version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - .:/var/www/html
      - stream-data:/var/www/html/storage/app/private/streams
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      QUEUE_CONNECTION: database
volumes:
  stream-data:
